---
- hosts: all
  become: yes
  tasks:    

    - name: Create virtual environment if it doesn't exist
      ansible.builtin.command: python3 -m venv "/home/{{ ansible_user }}/venv-flr"
      args:
        creates: "/home/{{ ansible_user }}/venv-flr"

    - name: Install required Python packages inside venv
      ansible.builtin.pip:
        executable: "/home/{{ ansible_user }}/venv-flr/bin/pip"
        name:
          - flwr
          - scikit-learn
          - pandas
          - numpy
        state: present
      
    - name: Install PyTorch inside venv
      ansible.builtin.pip:
        executable: "/home/{{ ansible_user }}/venv-flr/bin/pip"
        name: torch
        state: present

