apiVersion: v1
kind: Service
metadata:
  name: resource-lead-agent-lb
  namespace: swarmchestrate
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: resource-lead-agent
spec:
  type: LoadBalancer
  selector:
    app: resource-lead-agent
  ports:
    - name: raft
      protocol: TCP
      port: 8080        
      targetPort: 8080 
      nodePort: 30194
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31334