- name: Install k3s clusters
  hosts: all
  become: yes
  tasks:
    - name: Installing dependencies
      apt:
        name: curl
        state: present
        update_cache: yes




- name: Install k3s on control planes
  hosts: "*-control"
  become: yes
  tasks:
    - name: Install k3s on control plane
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server
      when: not inventory_hostname.startswith("cloud")
    
    - name: Get k3s token from control plane
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      when: not inventory_hostname.startswith("cloud")
    
- name: Install k3s on workers
  hosts: "*-worker"
  become: yes
  vars:
    k3s_port: 6443
  tasks:
    - name: Install k3s on workers
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://{{ hostvars[groups[cluster+'-control'][0]].private_ip }}:{{ k3s_port }} \
        K3S_TOKEN={{ hostvars[groups[cluster+'-control'][0]].k3s_token.stdout }} \
        sh -
      vars:
        cluster: "{{ inventory_hostname | regex_replace('-(worker|master)$', '') }}"
      when: not inventory_hostname.startswith("cloud")





  