- name: Install k3s clusters
  hosts: all
  become: yes
  tasks:
    - name: Installing dependencies
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Finde internal IP von NIC2 (enp0s9)
      command: ip -4 addr show dev enp0s9
      register: nic2_out

    - name: Setze internal_ip Fact
      set_fact:
        internal_ip: "{{ (nic2_out.stdout | regex_search('inet ([0-9\\.]+)', '\\1')) | first }}"

- name: Install k3s on control planes
  hosts: "*-control"
  become: yes
  tasks:
    - name: Install k3s on control plane
      shell: >
        INSTALL_K3S_EXEC="--node-ip {{ internal_ip }} --advertise-address {{ internal_ip }}" 
        sh -c 'curl -sfL https://get.k3s.io | sh -'
    
    - name: Get k3s token from control plane
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
  
- name: Install k3s auf Worker
  hosts: "*-worker"
  become: yes
  vars:
    k3s_port: 6443
  tasks:
    - name: Install k3s auf Worker
      environment:
        K3S_URL: "https://{{ hostvars[groups[inventory_hostname | regex_replace('-Worker$', '-control') | lower][0]].internal_ip }}:{{ k3s_port }}"
        K3S_TOKEN: "{{ hostvars[groups[inventory_hostname | regex_replace('-Worker$', '-control') | lower][0]].k3s_token.stdout }}"
        INSTALL_K3S_EXEC: "--node-ip {{ internal_ip }}"
      shell: curl -sfL https://get.k3s.io | sh -
   

    



