[cloud-energy-control]
cloud-energy-control ansible_host=20.39.41.4 private_ip=10.0.1.7

[cloud-energy-worker]
cloud-energy-worker ansible_host=172.190.185.131 private_ip=10.0.1.4

[edge-energy-control]
edge-energy-control ansible_host=20.39.50.134 private_ip=10.0.1.9

[edge-energy-worker]
edge-energy-worker ansible_host=172.190.62.168 private_ip=10.0.1.6

[fog-energy-control]
fog-energy-control ansible_host=172.171.216.162 private_ip=10.0.1.8

[fog-energy-worker]
fog-energy-worker ansible_host=172.190.157.79 private_ip=10.0.1.5

[all:vars]
ansible_user=furban
ansible_ssh_private_key_file=~/.ssh/az-key
ansible_python_interpreter=/usr/bin/python3
ansible_become=true