apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-lead-agent

data:
  config.yaml: |
    app:
      type: cloud
      schedulerinterval: 10
      applicationheartbeattimeout: 30
      nodeheartbeattimeout: 15

    httpserver:
      port: 8081
      gracefulshutdowntimeout: 5

    postgresdb:
      host: 10.0.1.5
      port: 5432
      user: foo
      pass: pass
      dbname: knowledge_base
      sslmode: disable
      timezone: UTC

    raft:
      id: 1
      peers:
        - http://10.0.1.41:8080


# Host of the DB is now the internal IP 
# User external IPs (which is a private IP) for the peers 