apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-resource-lead-agent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeAttributes:
      storageAccount: myclusterfiles
      shareName: cluster-share
    volumeHandle: myclusterfiles#cluster-share
    nodeStageSecretRef:
      name: azure-files-secret
      namespace: swarmchestrate