apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-lead-agent-raft
  namespace: swarmchestrate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-resource-lead-agent