# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
cloud-cost-control ansible_host=172.190.180.76  ip=10.0.1.4 etcd_member_name=etcd1

[etcd:children]
kube_control_plane

[kube_node]
cloud-cost-worker ansible_host=20.185.59.190  ip=10.0.1.10

[all:vars]
ansible_user=furban
ansible_ssh_private_key_file=~/.ssh/az-key
ansible_become=true
ansible_become_method=sudo