- name: Prüfe ob K3s auf den Control-Instanzen vorhanden ist
  hosts: "*-control"
  tasks:
    - name: Erstelle lokales Verzeichnis falls nicht vorhanden
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/.kube/az-cluster"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false
    
    - name: Verzeichnis /etc/rancher/k3s prüfen
      ansible.builtin.stat:
        path: /etc/rancher/k3s
      register: k3s_dir
      ignore_errors: yes
    
    - name: Abbrechen falls Verzeichnis fehlt
      ansible.builtin.fail:
        msg: "❌ K3s scheint nicht installiert zu sein! Verzeichnis /etc/rancher/k3s fehlt."
      when: 
        - not inventory_hostname.startswith("cloud")
        - k3s_dir.stat is defined and not k3s_dir.stat.exists
    
    - name: Prüfe zentrale K8s-Datei
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_file
      when: inventory_hostname.startswith("cloud")

    - name: Abbrechen, falls K8s Config-File fehlt
      ansible.builtin.fail:
        msg: "❌ Zentrale K8s-Datei fehlt auf {{ inventory_hostname }}!"
      when: 
        - inventory_hostname.startswith("cloud")
        - k8s_file.stat is defined and not k8s_file.stat.exists
    
    - name: Setze advertise_ip auf die IP aus dem Inventar
      ansible.builtin.set_fact:
        advertise_ip: "{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"
    
    - name: Schreibe config.yaml mit dynamischer advertise-address
      ansible.builtin.copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          advertise-address: {{ advertise_ip }}
          tls-san:
            - {{ advertise_ip }}
        owner: root
        group: root
        mode: '0644'
      when: not inventory_hostname.startswith("cloud")
    
    - name: Schreibe kubeadm ClusterConfiguration
      ansible.builtin.copy:
        dest: /etc/kubernetes/kubeadm-config.yaml
        content: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          controlPlaneEndpoint: "{{ advertise_ip }}:6443"
          apiServer:
            certSANs:
              - "{{ advertise_ip }}"
          networking:
            podSubnet: "10.244.0.0/16"
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname.startswith("cloud")
    
    - name: K3s neu starten
      ansible.builtin.systemd:
        name: k3s
        state: restarted
      when: 
        - k3s_dir.stat.exists
        - not inventory_hostname.startswith("cloud")
    
    - name: Kubernetes kubelet neu starten
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
      when: inventory_hostname.startswith("cloud")
    
    - name: Kopiere k3s.yaml vom Host auf den lokalen Rechner
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/.kube/az-cluster/{{ inventory_hostname | regex_replace('-control$', '') }}.yaml"
        flat: yes
      when: not inventory_hostname.startswith("cloud")
    
    - name: Kopiere kubeadm admin.conf vom Host auf den lokalen Rechner
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env','HOME') }}/.kube/az-cluster/{{ inventory_hostname | regex_replace('-control$', '') }}.yaml"
        flat: yes
      when: inventory_hostname.startswith("cloud")

    - name: Passe den API-Server-Port in allen Kubeconfigs an
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: 'server: https://.*:6443'
        replace: "server: https://localhost:{{ 6443 + index}}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false
    
    - name: Adjust context name
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)name:.*$'
        replace: "\\1name: {{ item | basename | regex_replace('-control$', '') | regex_replace('\\.yaml$', '') }}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false

    - name: Adjust cluster name
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)cluster:.*$'
        replace: "\\1cluster: {{ (item | basename | regex_replace('-control$', '')) | regex_replace('\\.yaml$', '')}}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false

    - name: Adjust user reference in context
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)user: default$'
        replace: "\\1user: user-{{ (item | basename | regex_replace('-control$', '')) | regex_replace('\\.yaml$', '') }}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false

    - name: Adjust user name
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)- name: default$'
        replace: "\\1- name: user-{{ (item | basename | regex_replace('-control$', '')) | regex_replace('\\.yaml$', '') }}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false
    
    - name: Adjust context user names in kubeconfig
      ansible.builtin.replace:
        path: "{{ item }}"
        # sucht nach Zeilen, die "user: kubernetes-admin" enthalten
        regexp: '^(\s*)user:\s*kubernetes-admin$'
        # ersetzt sie durch eindeutigen User basierend auf dem Dateinamen
        replace: "\\1user: user-{{ (item | basename | regex_replace('-control$', '')) | regex_replace('\\.yaml$', '') }}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false
    
    - name: Adjust user names in kubeconfig
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)- name:\s*kubernetes-admin$'
        replace: "\\1- name: user-{{ (item | basename | regex_replace('-control$', '')) | regex_replace('\\.yaml$', '') }}"
      loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.kube/az-cluster/*.yaml', wantlist=True) }}"
      loop_control:
        index_var: index
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false

    - name: kubeconfig Dateien zusammenführen
      ansible.builtin.shell: >
        KUBECONFIG=$(ls ~/.kube/az-cluster/*.yaml | tr '\n' ':') kubectl config view --flatten > ~/.kube/config
      args:
        executable: /bin/bash
      delegate_to: localhost
      run_once: true
      become: no
      vars:
        ansible_become: false