- name: Setup K3s Cluster for local management
  hosts: "*-control"
  become: yes

  tasks:
    - name: Ensure local folder exists for Kubeconfigs
      local_action:
        module: file
        path: "{{ lookup('env','HOME') }}/.kube/az-cluster"
        state: directory
        mode: '0755'

    - name: Check if /etc/rancher/k3s/k3s.yaml exists
      stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: k3s_yaml

    - name: Create /etc/rancher/k3s/config.yaml with advertise-address
      copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          advertise-address: "{{ ansible_host }}"
          tls-san:
            - "{{ ansible_host }}"
      when: k3s_yaml.stat.exists

    - name: Restart K3s
      systemd:
        name: k3s
        state: restarted
        enabled: yes
      when: k3s_yaml.stat.exists

    - name: Copy Kubeconfig to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/.kube/vbox-cluster/{{ inventory_hostname }}.yaml"
        flat: yes
