---
- name: Setup database
  hosts: central-management-vm         
  become: yes
  tasks:

    # - name: Ensure knowledge-base directory exists
    #   file:
    #     path: /home/{{ ansible_user }}/knowledge-base
    #     state: directory
    #     mode: '0755'
    
    # - name: Copy migrations-db directory to remote host
    #   copy:
    #     src: "{{ playbook_dir }}/../migrations-db/"
    #     dest: /home/{{ ansible_user }}/knowledge-base/
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: '0755'
    
    - name: Apply SQL migration scripts
      shell: |
        for file in /home/{{ ansible_user }}/knowledge-base/*.up.sql; do
          PGPASSWORD=pass psql -h localhost -U foo -d knowledge_base -f "$file";
        done