- name: setup-postgre
  hosts: central-management-vm
  become: yes
  tasks:    
    - name: Install psycopg2 for Python3
      pip:
        name: psycopg2-binary
        executable: pip3

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create remote_tmp for PostgreSQL
      file:
        path: /var/lib/postgresql/.ansible/tmp
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'